### PR TITLE
Go modules support

### LINKED ISSUE #213: New release?
We're shipping the latest release of wellington in Homebrew, but now it doesn't build anymore since it's not compatible with latest go (while master is). Could you please cut a new release?

### PR DESCRIPTION
**Pull request by ydnar**
This PR enables Wellington to build and run on a modern version of Go, currently tested with Go 1.14. Fixes #213.

This should also help unblock these downstream issues in Homebrew, notably blocking the Go 1.14.1 release:

https://github.com/Homebrew/homebrew-core/issues/52184
https://github.com/Homebrew/homebrew-core/pull/51909

### CODE REVIEW

**Comment by ydnar** [comment]
All right.

**Comment by drewwells** [comment]
Thanks Ill open another PR to add back vendors so it works without go mod

**Comment by ydnar** [comment]
Great, thanks. What dependencies did it need a `vendor` dir for?

**Comment by jnozsc** [comment]
First of all, thanks for this PR.

however, it seems applying this PR only to the `v1.0.4` release may be not enough

https://github.com/Homebrew/homebrew-core/pull/59428

Would you mind making a new release? as `v1.0.5`

Thanks

**Comment by jnozsc** [comment]
cc @drewwells

**Pull request merged**
